[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Peter", email = "forsuse@live.de" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "pydantic-settings>=2.15.0",
    "pyyaml>=6.0.3",
    "uvicorn>=0.54.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
