kind: project
emit:
  - "@typespec/json-schema"
  - "@typespec/openapi3"
options:
  "@typespec/json-schema":
    emitter-output-dir: "{cwd}/../data/$schema"
  "@typespec/openapi3":
    emitter-output-dir: "{cwd}/../backend/generated"
    output-file: "openapi.yaml"