/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Devices_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Services_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Action: {
            /** @description Delay in ms to wait before executing this action */
            delay?: number;
            /** @description Discriminator property for Action. */
            type: string;
        };
        Assertion: {
            /** @description Discriminator property for Assertion. */
            type: string;
        };
        Checklist: {
            interval: number;
            up: components["schemas"]["Assertion"];
            startings?: components["schemas"]["Assertion"];
        };
        Device: {
            name: string;
            description: string;
            flags: string[];
            image: string;
            attributes: {
                [key: string]: unknown;
            };
        };
        HttpGetAction: {
            /** @enum {string} */
            type: "HTTP";
            /** @enum {string} */
            method: "GET" | "POST" | "PUT" | "DELETE";
            url: string;
        } & (Omit<WithRequired<components["schemas"]["Action"], "type">, "type"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HTTP";
        });
        JsonFromHttpAssertion: {
            /** @enum {string} */
            type: "JSON_FROM_HTTP";
            url: string;
            /** @enum {string} */
            method: "GET" | "POST" | "PUT" | "DELETE";
            path: string;
            /** @enum {string} */
            operation: "ne" | "eq";
            value: unknown;
        } & (Omit<WithRequired<components["schemas"]["Assertion"], "type">, "type"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "JSON_FROM_HTTP";
        });
        Service: {
            name: string;
            description: string;
            checks: components["schemas"]["Checklist"];
            actions: {
                [key: string]: components["schemas"]["Action"][];
            };
        };
        ServiceSummary: {
            id: string;
            name: string;
            description: string;
            actions: string[];
            /** @enum {string} */
            status: "up" | "starting" | "down";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Action = components['schemas']['Action'];
export type Assertion = components['schemas']['Assertion'];
export type Checklist = components['schemas']['Checklist'];
export type Device = components['schemas']['Device'];
export type HttpGetAction = components['schemas']['HttpGetAction'];
export type JsonFromHttpAssertion = components['schemas']['JsonFromHttpAssertion'];
export type Service = components['schemas']['Service'];
export type ServiceSummary = components['schemas']['ServiceSummary'];
export type $defs = Record<string, never>;
export interface operations {
    Devices_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
        };
    };
    Services_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceSummary"][];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
